### ISSUE TITLE
broken for objects

### ISSUE THREAD

**Issue by johndeighan** [soygul/js-api#11]
Only seems to be able to return arrays as JSON, not objects. E.g., use this in your simple example:

let data = {
	posts: {
		all: [
			{id: 'p1', title: 'first post', body: 'lorem ipsum'},
			],
		},
	};

When you request http://localhost:3000/posts, you'll get:

[[{"id":"p1","title":"first post","body":"lorem ipsum"}]]

which is wrong. I realize this project is old, but you should either fix it or take it down.

**Comment by soygul** [comment]
Good point. I specifically designed this project for tabular data so I didn't consider plain objects.

I've just added support for plain objects in the newest version of `js-api`. You can pull the new package from NPM or just update to latest master from git. Thanks for notifying me or otherwise I wouldn't have noticed.
